### ISSUE TITLE
Fix Audio 

### ISSUE THREAD

**Issue by walkerlj0** [link-rot-project/syriastreet.com#3]
Currently, the Audio isn't working on the mirror of the syriastreet site. There are 3 sections where audio should auto-play as you scroll over. Fix please!

See notes here: https://app.mural.co/t/starlinglab7814/m/starlinglab7814/1692384958504/ec86a0b27af03f534f74d2d6687f6c5d2f42a3d9?sender=ub3a421c048efd7d270741703

**Comment by sutty-coop** [comment]
The issue with auto-playing audio is that browsers forbid this explicitly when there's no user interaction (or what they consider it to be).

For instance, I can see this on the console while I'm scrolling https://syriastreet.brandontauszik.com/

![image](https://github.com/link-rot-project/syriastreet.com/assets/113475467/e5e887cb-1f05-4245-8969-4141ee909111)

**Comment by sutty-coop** [comment]
If you load the site and click on it before scrolling, audio works, because the browsers considers you interacted with it.

**Comment by walkerlj0** [comment]
@brandontauszik the audio will only play if you click somewhere in the browser first (this is a setting by the browser) -- is that good enough?

**Comment by brandontauszik** [comment]
If there’s nothing that can be coded to change that, then I think that will have to be good enough right?~ brandontauszik.com ~On Sep 15, 2023, at 1:27 PM, Lindsay Walker ***@***.***> wrote:﻿
@brandontauszik the audio will only play if you click somewhere in the browser first (this is a setting by the browser) -- is that good enough?

**Comment by walkerlj0** [comment]
current behavior is good
