### ISSUE TITLE
Publish website on Distributed Press

### ISSUE THREAD

**Issue by sutty-coop** [link-rot-project/syriastreet.com#5]
Same as https://github.com/link-rot-project/facing.life/issues/11

**Comment by fauno** [comment]
@walkerlj0 this is ready but we need to set the DNS info, let me know when we can meet

**Comment by walkerlj0** [comment]
@fauno it looks like we have a meeting at 3pm PST Friday on Oct 13th
note - it looks like the staging site is down now? https://syriastreet.testing.sutty.nl/

**Comment by sutty-coop** [comment]
> it looks like the staging site is down now? https://syriastreet.testing.sutty.nl/

it works for me, what error did you see?

**Comment by walkerlj0** [comment]
@sutty-coop this is what I'm getting []()![Screenshot_20231012-100438.png](https://github.com/link-rot-project/syriastreet.com/assets/66978602/08be4899-e7cc-450a-88ab-5d78e91904f2)

**Comment by fauno** [comment]
Can you try on an incognito tab and let me know if it works?

**Comment by fauno** [comment]
@walkerlj0 @brandontauszik DNS records to add to brandontauszik.com

```
syriastreet CNAME api.distributed.press.
_dnslink.syriastreet NS api.distributed.press.
```

TTL value should be the lowest possible, so any changes on api.distributed.press. apply shortly after they change.

**Comment by walkerlj0** [comment]
Done, changed DNS on godaddy for subdomain
